apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: hello-go
  namespace: default
spec:
  interval: 10m0s
  releaseName: hello-go
  chart:
    spec:
      chart: hello-go-web
      version: 0.8.0
      sourceRef:
        kind: HelmRepository
        name: 418-cloud
  values:
    url: azr.418.cloud
    traefik:
      enabled: true
      entryPoints:
        - web
        - websecure
      tls: 
        secretName: azr-418-cloud-cert
        domains:
          main: azr.418.cloud