apiVersion: k8s.418.cloud/v1alpha1
kind: TeapotApp
metadata:
  name: teapotapp-sample
  namespace: default
  labels:
    teapot: sample-app
spec:
  image: ghcr.io/418-cloud/testapp:v0.0.1
  path: /simple
  args:
  - -rootContext=/simple
  - -response=Hi, my deploy yaml is a bit shorter
  - title=418 demo